services:
  firebase-emulators:
    image: andreysenov/firebase-tools:latest
    ports:
      - "3479:3479"   # Emulator UI
      - "3477:3477"   # Auth
      - "3476:3476"   # Firestore
      - "3478:3478"   # Storage
    volumes:
      - ./:/home/node
      - firebase-data:/home/node/.firebase
    working_dir: /home/node
    command: firebase emulators:start --only auth,firestore,storage --project vintage-c534e --import=/home/node/.firebase --export-on-exit=/home/node/.firebase
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx2g

volumes:
  firebase-data:
